
import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{initializeApp}from"firebase/app";
import{getAuth,signInAnonymously}from"firebase/auth";
import{getFirestore,collection,addDoc,onSnapshot,query,where,orderBy,serverTimestamp,setDoc,doc,updateDoc,getDocs}from"firebase/firestore";
import"./style.css";

const SUPPORT="7678256489", MASTER="devindra-master";
const cfg={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN||"devindra-mart-main-21205.firebaseapp.com",projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID||"devindra-mart-main-21205",storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET||"devindra-mart-main-21205.firebasestorage.app",messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID||"513697622138",appId:import.meta.env.VITE_FIREBASE_APP_ID,measurementId:import.meta.env.VITE_FIREBASE_MEASUREMENT_ID||"G-SLX40MKP4D"};
const ready=!!(cfg.apiKey&&cfg.appId);let app=null,auth=null,db=null;try{if(ready){app=initializeApp(cfg);auth=getAuth(app);db=getFirestore(app)}}catch(e){console.warn(e)}
const demoProducts=[
{id:"p1",product:"Fortune Sunlite Oil",category:"Tel/Oil",unit:"Packet",loosePrice:150,cartonPrice:1620,stock:25,badge:"Best Value",storeId:MASTER},
{id:"p2",product:"Aashirvaad Atta 5kg",category:"Atta",unit:"Bag",loosePrice:240,cartonPrice:1200,stock:18,badge:"Scheme Active",storeId:MASTER},
{id:"p3",product:"India Gate Rice 1kg",category:"Rice",unit:"Packet",loosePrice:120,cartonPrice:1100,stock:20,badge:"Offer",storeId:MASTER},
{id:"p4",product:"Tata Salt 1kg",category:"Grocery",unit:"Packet",loosePrice:20,cartonPrice:360,stock:4,badge:"Low Stock",storeId:MASTER}
];
async function login(role){localStorage.setItem("dm_role",role);if(!auth)return"local-"+role;let r=await signInAnonymously(auth);await setDoc(doc(db,"users",r.user.uid),{uid:r.user.uid,role,active:true,updatedAt:serverTimestamp()},{merge:true});localStorage.setItem("dm_uid",r.user.uid);return r.user.uid}
function code(){let d=new Date();let date=String(d.getFullYear()).slice(2)+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0");return"WAR-"+date+"-"+Math.floor(1000+Math.random()*9000)}
function listenProducts(cb){if(!db){cb(JSON.parse(localStorage.getItem("dm_products")||"null")||demoProducts);return()=>{}}return onSnapshot(collection(db,"products"),s=>{let a=s.docs.map(d=>({id:d.id,...d.data()}));cb(a.length?a:demoProducts)},()=>cb(demoProducts))}
function listenOrders(cb,storeId){if(!db){cb(JSON.parse(localStorage.getItem("dm_orders")||"[]"));return()=>{}}let q=storeId?query(collection(db,"orders"),where("storeId","==",storeId),orderBy("createdAt","desc")):query(collection(db,"orders"),orderBy("createdAt","desc"));return onSnapshot(q,s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),()=>cb([]))}
async function seed(){if(!db){localStorage.setItem("dm_products",JSON.stringify(demoProducts));alert("Local products seeded");return}let ex=await getDocs(collection(db,"products"));if(ex.empty){for(const p of demoProducts)await addDoc(collection(db,"products"),{...p,active:true,createdAt:serverTimestamp()})}alert("Firestore products seeded")}
async function addProduct(p){if(!db){let a=JSON.parse(localStorage.getItem("dm_products")||"[]");a.unshift({...p,id:"local-"+Date.now()});localStorage.setItem("dm_products",JSON.stringify(a));return}await addDoc(collection(db,"products"),{...p,active:true,createdAt:serverTimestamp()})}
async function order(items){let subtotal=items.reduce((s,i)=>s+Number(i.loosePrice||0)*Number(i.qty||1),0),delivery=subtotal>=1000?0:50;let o={orderId:"INV-"+new Date().getFullYear()+"-"+Date.now().toString().slice(-6),customerId:localStorage.getItem("dm_uid")||"local-customer",customerName:"Customer",address:"Warishnagar",phone:SUPPORT,storeId:MASTER,storeName:"Devindra Mart Wholesale",items,subtotal,delivery,total:subtotal+delivery,status:"placed",pickupCode:code(),createdAt:db?serverTimestamp():Date.now()};if(!db){let a=JSON.parse(localStorage.getItem("dm_orders")||"[]");a.unshift({...o,id:"local-"+Date.now()});localStorage.setItem("dm_orders",JSON.stringify(a));return o}return addDoc(collection(db,"orders"),o)}
async function upd(id,data){if(!db||String(id).startsWith("local")){let a=JSON.parse(localStorage.getItem("dm_orders")||"[]").map(o=>o.id===id?{...o,...data}:o);localStorage.setItem("dm_orders",JSON.stringify(a));return}return updateDoc(doc(db,"orders",id),{...data,updatedAt:serverTimestamp()})}
async function cloud(file){let cn=import.meta.env.VITE_CLOUDINARY_CLOUD_NAME||"dmwznjgvr",pr=import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET||"devindra_upload";let fd=new FormData();fd.append("file",file);fd.append("upload_preset",pr);fd.append("folder","devindra-mart");let r=await fetch(`https://api.cloudinary.com/v1_1/${cn}/auto/upload`,{method:"POST",body:fd});let data=await r.json();if(!data.secure_url)throw Error("upload failed");return data.secure_url}
function Shell({t,s,i,nav,children}){return <><header className="top"><div className="brand"><div className="logo">DM</div><div><h2>{t}</h2><p>{s}</p></div></div><b className="mode">{ready?"LIVE FIREBASE":"LOCAL MODE"}</b><div className="topIcon">{i}</div></header><main className="wrap">{children}</main><nav className="bottom">{nav.map(x=><span key={x}>{x}</span>)}</nav></>}
function Customer(){let[products,setProducts]=useState([]),[cart,setCart]=useState([]);useEffect(()=>{login("customer");return listenProducts(setProducts)},[]);let add=p=>setCart(c=>{let f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,qty:(x.qty||1)+1}:x):[...c,{...p,qty:1}]});let place=async()=>{if(!cart.length)return alert("Cart empty");await order(cart);setCart([]);alert("Order placed. Billing app me live dikhega.")};return <Shell t="Devindra Mart" s="Customer App" i="🔔" nav={["🏠 Home","▦ Categories","🛒 Cart","📒 Khata","👤 Profile"]}><section className="hero"><div><h1>Devindra Mart Wholesale</h1><p>Customer app only. Admin/Billing/Rider links yahan nahi dikhte.</p></div><div className="heroEmoji">🛒</div></section><div className="notice">Support: {SUPPORT}. WhatsApp order only Devindra Mart Wholesale.</div><button onClick={seed}>Seed Products/Stores</button><div className="search">🔍 Search products, brands, categories... 🎙️</div><div className="chips">{["🛢️ Tel/Oil","🍚 Chawal","🌾 Atta","🥣 Dal","🧂 Masale"].map(x=><div className="chip" key={x}>{x}</div>)}</div><div className="head"><h2>Products</h2><button onClick={place}>Place Order ({cart.length})</button></div><section className="grid">{products.map(p=><div className="card product" key={p.id}><div className="pimg">📦</div><div><span className="tag">{p.badge}</span><h3>{p.product}</h3><p>{p.category} • {p.unit}</p><p className="price">₹{p.loosePrice}</p><button onClick={()=>add(p)}>Add</button></div></div>)}</section></Shell>}
function Admin(){let[orders,setOrders]=useState([]),[products,setProducts]=useState([]);useEffect(()=>{login("admin");let a=listenOrders(setOrders),b=listenProducts(setProducts);return()=>{a();b()}},[]);let add=async()=>{await addProduct({product:"Admin Product "+Date.now().toString().slice(-3),category:"Grocery",unit:"Packet",loosePrice:99,cartonPrice:900,stock:50,badge:"New",storeId:MASTER});alert("Product added")};let up=async e=>{let f=e.target.files?.[0];if(!f)return;alert(await cloud(f))};return <Shell t="Devindra Admin" s="Master Control" i="🛡️" nav={["📊 Dashboard","🏪 Stores","🛵 Riders","⚙️ Settings"]}><section className="hero"><div><h1>Admin Panel</h1><p>Full control. Other app switch links hidden.</p></div><div className="heroEmoji">🛡️</div></section><div className="stats"><div className="stat"><p>Orders</p><b>{orders.length}</b></div><div className="stat"><p>Products</p><b>{products.length}</b></div><div className="stat"><p>Support</p><b>7678</b></div><div className="stat"><p>Status</p><b>Live</b></div></div><section className="grid"><div className="card"><h3>Seed Database</h3><p>Stores + products create karo.</p><button onClick={seed}>Seed Now</button></div><div className="card"><h3>Product Control</h3><p>Add product to Firestore.</p><button onClick={add}>Add Product</button></div><div className="card"><h3>Cloudinary Upload</h3><input type="file" onChange={up}/></div><div className="card"><h3>Live Orders</h3>{orders.slice(0,4).map(o=><p key={o.id}>{o.orderId} — ₹{o.total}</p>)}</div></section></Shell>}
function Billing(){let[orders,setOrders]=useState([]);useEffect(()=>{login("billing");return listenOrders(setOrders,MASTER)},[]);return <Shell t="Devindra Billing" s="Merchant/Billing" i="🧾" nav={["📥 Orders","📦 Products","🧾 Invoice","💰 Ledger"]}><section className="hero"><div><h1>Billing / Merchant App</h1><p>Own-store order panel. Admin/Customer/Rider links hidden.</p></div><div className="heroEmoji">🧾</div></section><div className="notice">Packing slip me customer full address hide logic ready.</div><section className="grid">{orders.length?orders.map(o=><div className="card" key={o.id}><h3>{o.orderId}</h3><p>Total ₹{o.total}</p><p>Status: {o.status}</p><p>Pickup: {o.pickupCode}</p><button onClick={()=>upd(o.id,{status:"ready"})}>Mark Ready</button></div>):<div className="card"><h3>No Orders</h3><p>Customer app se order place karo.</p></div>}</section></Shell>}
function Rider(){let[orders,setOrders]=useState([]),[code,setCode]=useState("");useEffect(()=>{login("rider");return listenOrders(setOrders)},[]);let unlocked=orders.filter(o=>o.pickupCode===code);return <Shell t="Devindra Rider" s="Code Unlock Delivery" i="🛵" nav={["🏠 Home","🔐 Unlock","📦 Orders","💰 Earnings"]}><section className="hero"><div><h1>Rider App</h1><p>Without pickup code/QR, no order details visible.</p></div><div className="heroEmoji">🛵</div></section><div className="notice red">Rider ko code ke bina name/address/items/amount/map hidden.</div><section className="grid"><div className="card"><h3>Enter Pickup Code</h3><input className="input" value={code} onChange={e=>setCode(e.target.value)} placeholder="WAR-YYMMDD-1234"/><p>Ready orders: {orders.length}</p></div>{unlocked.map(o=><div className="card" key={o.id}><h3>Unlocked: {o.orderId}</h3><p>{o.customerName}</p><p>{o.address}</p><p>₹{o.total}</p><button onClick={()=>upd(o.id,{status:"delivered"})}>Delivered</button></div>)}{!unlocked.length&&<div className="card"><h3>🔒 Locked</h3><p>No details visible until correct code.</p></div>}</section></Shell>}
function App(){let p=location.pathname;if(p.startsWith("/admin"))return <Admin/>;if(p.startsWith("/billing"))return <Billing/>;if(p.startsWith("/rider"))return <Rider/>;return <Customer/>}
createRoot(document.getElementById("root")).render(<App/>);
