const DM={
 logo:'/assets/logo-premium.png', icon:'/assets/app-icon.jpg', banner:'/assets/banner-main.jpg',
 lang:localStorage.dmLang||'hinglish', cart:JSON.parse(localStorage.dmCart||'[]'),
 products:[
 {id:'P001',cat:'Grocery',sub:'Atta',name:'Aashirvaad Atta 10kg Bora',brand:'Aashirvaad',variant:'10kg',unit:'Bora',loose:395,carton:2280,stock:50,img:'https://images.unsplash.com/photo-1621955964441-c173e01c135b?auto=format&fit=crop&w=600&q=80',scheme:'Bulk Save'},
 {id:'P002',cat:'Oil',sub:'Mustard Oil',name:'Fortune Mustard Oil 1L Bottle',brand:'Fortune',variant:'1L',unit:'Bottle',loose:145,carton:1680,stock:72,img:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',scheme:'Carton Rate'},
 {id:'P003',cat:'Snacks',sub:'Chocolate',name:'Dairy Milk Chocolate Packet',brand:'Cadbury',variant:'₹10',unit:'Packet',loose:10,carton:480,stock:300,img:'https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=600&q=80',scheme:'MRP ₹10'},
 {id:'P004',cat:'Rice',sub:'Basmati',name:'Basmati Rice 25kg Bora',brand:'Premium',variant:'25kg',unit:'Bora',loose:1699,carton:1699,stock:18,img:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',scheme:'Wholesale'}],
 stores:[{id:'S1',name:'Devindra Mart Wholesale',type:'wholesale',cat:'Grocery',km:.8,whatsapp:'917678256489',main:true},{id:'S2',name:'Maa Retail Store',type:'retail',cat:'Grocery',km:1.2},{id:'S3',name:'Ganesh Electronics',type:'retail',cat:'Electronics',km:2.1}],
 orders:JSON.parse(localStorage.dmOrders||'[]'), riders:JSON.parse(localStorage.dmRiders||'[]')
};
function save(){localStorage.dmCart=JSON.stringify(DM.cart);localStorage.dmOrders=JSON.stringify(DM.orders);localStorage.dmRiders=JSON.stringify(DM.riders);}
function t(key){const dict={hinglish:{search:'Search karo',add:'Add to Cart',remove:'Remove',summary:'View Summary',order:'Order Now',whatsapp:'Order on WhatsApp',cart:'Cart',home:'Home',more:'More',profile:'Profile',pay:'Payment',khata:'Khata',voice:'Voice Order',parcha:'Parcha Upload'},en:{search:'Search',add:'Add to Cart',remove:'Remove',summary:'View Summary',order:'Order Now',whatsapp:'Order on WhatsApp',cart:'Cart',home:'Home',more:'More',profile:'Profile',pay:'Payment',khata:'Khata',voice:'Voice Order',parcha:'Parcha Upload'},hi:{search:'खोजें',add:'Add to Cart',remove:'Remove',summary:'View Summary',order:'Order Now',whatsapp:'Order on WhatsApp',cart:'Cart',home:'होम',more:'More',profile:'Profile',pay:'Payment',khata:'खाता',voice:'Voice Order',parcha:'Parcha Upload'}};return (dict[DM.lang]||dict.hinglish)[key]||key}
function header(title,sub='Wholesale + Retail Marketplace'){return `<div class="top"><img class="logo" src="${DM.logo}"><div><div class="brand">${title}</div><div class="sub">${sub}</div></div><div class="spacer"></div><select style="max-width:120px" onchange="localStorage.dmLang=this.value;location.reload()"><option ${DM.lang==='hinglish'?'selected':''} value="hinglish">Hinglish</option><option ${DM.lang==='en'?'selected':''} value="en">English</option><option ${DM.lang==='hi'?'selected':''} value="hi">हिन्दी</option></select></div>`}
function showInstall(){if(location.pathname.includes('admin'))return; if(matchMedia('(display-mode: standalone)').matches||localStorage.dmInstalled)return; const d=document.createElement('div');d.className='install';d.innerHTML=`<img src="${DM.icon}" style="width:42px;height:42px;border-radius:10px"><b>Install Devindra Mart App</b><div class="spacer"></div><button class="btn green" onclick="localStorage.dmInstalled=1;this.closest('.install').remove()">Install Now</button>`;document.body.appendChild(d)}
function addCart(id){let p=DM.products.find(x=>x.id===id);let e=DM.cart.find(x=>x.id===id);e?e.qty++:DM.cart.push({...p,qty:1});save();toast('Cart me add ho gaya')}
function toast(msg){let d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;top:18px;left:50%;transform:translateX(-50%);background:#111;color:white;padding:12px 18px;border-radius:999px;z-index:99';document.body.appendChild(d);setTimeout(()=>d.remove(),1700)}
function makeOrder(source='app',storeId='S1'){const items=[...DM.cart]; if(!items.length){toast('Cart empty hai');return} let total=items.reduce((s,x)=>s+x.loose*x.qty,0); let o={id:'DM'+Date.now().toString().slice(-6),source,storeId,items,total,delivery:total>=5000?0:total>=3000?10:total>=1000?20:50,status:'Placed',payment:'COD',created:new Date().toLocaleString(),pickupQR:'locked',riderStatus:'Not assigned'};DM.orders.unshift(o);DM.cart=[];save();return o}
function whatsappOrder(){let store=DM.stores[0];let o=makeOrder('whatsapp',store.id); if(!o)return; let msg=`🛒 New Order - Devindra Mart%0A%0AOrder ID: ${o.id}%0AItems:%0A${o.items.map(i=>'• '+i.name+' x '+i.qty+' = ₹'+(i.loose*i.qty)).join('%0A')}%0A%0ATotal: ₹${o.total+o.delivery}%0APayment: COD`; window.open(`https://wa.me/${store.whatsapp}?text=${msg}`,'_blank');}
function nav(role){let base=role==='customer'?['/','Home','Cart','More']:role==='admin'?['/admin/','Dashboard','Orders','Settings']:role==='billing'?['/billing/','Orders','Print','Tools']:['/rider/','Pickup','Scan QR','Cash'];return `<div class="nav"><a href="${base[0]}">${base[1]}</a><button onclick="toast('${base[2]}')">${base[2]}</button><button onclick="toast('${base[3]}')">${base[3]}</button><button onclick="toast('Profile')">Profile</button></div>`}
window.addEventListener('load',showInstall);
