import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously } from 'firebase/auth';
import { getFirestore, collection, addDoc, onSnapshot, query, where, orderBy, serverTimestamp, setDoc, doc, updateDoc, getDocs, writeBatch } from 'firebase/firestore';
import './style.css';

const SUPPORT = import.meta.env.VITE_SUPPORT_NUMBER || '7678256489';
const WHATSAPP = import.meta.env.VITE_WHATSAPP_ORDER_NUMBER || '917678256489';
const MASTER = 'devindra-master';
const CART_KEY = 'dm_cart';
const CUSTOMER_KEY = 'dm_customer_profile';
const ADDRESS_KEY = 'dm_customer_address';
const LANG_KEY = 'dm_lang';

const cfg = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || 'AIzaSyA4y5n3BhbgIvE1-owBqO0fFycrKXi2grw',
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || 'devindra-mart-main-21205.firebaseapp.com',
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || 'devindra-mart-main-21205',
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || 'devindra-mart-main-21205.firebasestorage.app',
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '513697622138',
  appId: import.meta.env.VITE_FIREBASE_APP_ID || '1:513697622138:web:a150445a5abe1d9985b3c3',
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || 'G-SLX40MKP4D'
};
let app = null, auth = null, db = null;
try { app = initializeApp(cfg); auth = getAuth(app); db = getFirestore(app); } catch (e) { console.warn('connection unavailable'); }

const T = {
  hinglish: { search:'Search products, brands, categories...', view:'View Cart', cart:'My Cart', subtotal:'Subtotal', delivery:'Delivery', total:'Total', empty:'Cart is empty', whatsapp:'Order on WhatsApp', order:'Order Now', min:'Minimum order value is ₹500', success:'Order sent successfully ✅', khata:'Mera Hisab', due:'Total Due', trust:'⭐ Aapka trust improve ho raha hai 👍' },
  hindi: { search:'Product, brand, category खोजें...', view:'कार्ट देखें', cart:'मेरा कार्ट', subtotal:'सबटोटल', delivery:'डिलीवरी', total:'कुल', empty:'कार्ट खाली है', whatsapp:'WhatsApp पर ऑर्डर', order:'ऑर्डर करें', min:'न्यूनतम ऑर्डर ₹500 है', success:'ऑर्डर सफल ✅', khata:'मेरा हिसाब', due:'कुल बकाया', trust:'⭐ आपका भरोसा बेहतर हो रहा है 👍' },
  english: { search:'Search products, brands, categories...', view:'View Cart', cart:'My Cart', subtotal:'Subtotal', delivery:'Delivery', total:'Total', empty:'Cart is empty', whatsapp:'Order on WhatsApp', order:'Order Now', min:'Minimum order value is ₹500', success:'Order sent successfully ✅', khata:'My Khata', due:'Total Due', trust:'⭐ Your trust is improving 👍' }
};

const defaultSettings = {
  appName:'Devindra Mart', tagline:'Ab ghar tak paaye bazaar jaise rate', notice:'Fresh deals today • Minimum order ₹500 • Fast delivery',
  supportNumber:SUPPORT, whatsappNumber:WHATSAPP, minimumOrder:500, founder:'Aditya Jha', upi:'upi@upi', masterStoreId:MASTER,
  deliveryRules:{ wholesale:[{upto:999,charge:50},{upto:2999,charge:30},{upto:4999,charge:20},{upto:9999999,charge:10}], retail:{fixed:20, perKm:10, min:10}},
  commission:{type:'percent', value:10}, riderPayout:{salary:8000, perOrder:5, perKm:0, area:{Warishnagar:20,Khanpur:25,Village:35}}, adOn:true, theme:'blue'
};
const storesSeed = [
  { id:MASTER, name:'Devindra Mart Wholesale', mode:'wholesale', area:'Warishnagar • Khanpur', whatsappOrder:true, khata:true, visible:true, settlementFee:10 },
  { id:'retail-kirana-1', name:'Nearby Kirana Store', mode:'retail', area:'Market Area', whatsappOrder:false, khata:false, visible:false, settlementFee:12 }
];
const catalogSeed = [
  { id:'fortune-oil', storeId:MASTER, category:'Tel/Oil', subcategory:'Refined Oil', product:'Fortune Sunlite Oil', brand:'Fortune', image:'/assets/products/fortune-oil.png', badge:'Best Value', variants:[{label:'1L Piece',unit:'Piece',loosePrice:150,cartonPrice:1620,stock:36},{label:'5L Tin',unit:'Tin',loosePrice:720,cartonPrice:4200,stock:12},{label:'Carton',unit:'Carton',loosePrice:1620,cartonPrice:1620,stock:8}], scheme:'Carton lena sasta padega' },
  { id:'atta', storeId:MASTER, category:'Aata/Atta', subcategory:'Wheat Flour', product:'Aashirvaad Atta', brand:'Aashirvaad', image:'/assets/products/aashirvaad-atta.png', badge:'Scheme Active', variants:[{label:'5kg Bag',unit:'Bag',loosePrice:240,cartonPrice:1200,stock:20},{label:'10kg Bag',unit:'Bag',loosePrice:465,cartonPrice:1380,stock:14},{label:'Carton',unit:'Carton',loosePrice:1200,cartonPrice:1200,stock:7}], scheme:'Atta + Oil + Rice combo available' },
  { id:'rice', storeId:MASTER, category:'Chawal/Rice', subcategory:'Basmati', product:'India Gate Rice', brand:'India Gate', image:'/assets/products/india-gate-rice.png', badge:'Offer', variants:[{label:'1kg Packet',unit:'Packet',loosePrice:120,cartonPrice:1100,stock:42},{label:'5kg Bag',unit:'Bag',loosePrice:570,cartonPrice:2200,stock:16},{label:'Carton',unit:'Carton',loosePrice:1100,cartonPrice:1100,stock:9}], scheme:'' },
  { id:'salt', storeId:MASTER, category:'Kirana', subcategory:'Salt', product:'Tata Salt', brand:'Tata', image:'/assets/products/tata-salt.png', badge:'Low Stock', variants:[{label:'1kg Packet',unit:'Packet',loosePrice:20,cartonPrice:360,stock:6},{label:'Carton',unit:'Carton',loosePrice:360,cartonPrice:360,stock:3}], scheme:'' },
  { id:'surf', storeId:MASTER, category:'Household', subcategory:'Detergent', product:'Surf Excel', brand:'HUL', image:'/assets/products/surf-excel.png', badge:'Offer', variants:[{label:'500g Packet',unit:'Packet',loosePrice:68,cartonPrice:1200,stock:18},{label:'2kg Packet',unit:'Packet',loosePrice:285,cartonPrice:3200,stock:11}], scheme:'' },
  { id:'tea', storeId:MASTER, category:'Grocery', subcategory:'Tea', product:'Tata Tea Premium', brand:'Tata', image:'/assets/products/tata-tea.png', badge:'Best Value', variants:[{label:'250g Packet',unit:'Packet',loosePrice:95,cartonPrice:1800,stock:25},{label:'1kg Packet',unit:'Packet',loosePrice:360,cartonPrice:3900,stock:10}], scheme:'' },
  { id:'parle', storeId:MASTER, category:'Snacks', subcategory:'Biscuit', product:'Parle-G Biscuit', brand:'Parle', image:'/assets/products/parle-g.png', badge:'MRP ₹5', variants:[{label:'₹5 Pack',unit:'Packet',loosePrice:5,cartonPrice:480,stock:100},{label:'Carton',unit:'Carton',loosePrice:480,cartonPrice:480,stock:13}], scheme:'' },
  { id:'cola', storeId:'retail-kirana-1', category:'Cold Drink', subcategory:'Beverage', product:'Cold Drink', brand:'Retail', image:'/assets/products/cold-drink.png', badge:'Nearby', variants:[{label:'250ml Bottle',unit:'Piece',loosePrice:20,cartonPrice:0,stock:24},{label:'750ml Bottle',unit:'Piece',loosePrice:45,cartonPrice:0,stock:12}], scheme:'' }
];

async function roleLogin(role='customer'){
  localStorage.setItem('dm_role', role);
  if(!auth) return 'local-'+role;
  const r = await signInAnonymously(auth);
  await setDoc(doc(db,'users',r.user.uid), {uid:r.user.uid, role, active:true, updatedAt:serverTimestamp()}, {merge:true});
  localStorage.setItem('dm_uid', r.user.uid);
  return r.user.uid;
}
function useLiveProducts(){ const [items,setItems] = useState(catalogSeed); useEffect(()=>{ if(!db){ setItems(JSON.parse(localStorage.getItem('dm_products')||'null')||catalogSeed); return; } return onSnapshot(collection(db,'products'), s=>{ const a=s.docs.map(d=>({id:d.id,...d.data()})); setItems(a.length?a:catalogSeed); },()=>setItems(catalogSeed)); },[]); return items; }
function useLiveOrders(storeId=null){ const [orders,setOrders] = useState([]); useEffect(()=>{ if(!db){ setOrders(JSON.parse(localStorage.getItem('dm_orders')||'[]')); return; } let q = storeId ? query(collection(db,'orders'), where('storeId','==',storeId), orderBy('createdAt','desc')) : query(collection(db,'orders'), orderBy('createdAt','desc')); return onSnapshot(q, s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()}))),()=>{}); },[storeId]); return orders; }
async function seedDatabase(){ if(!db){ localStorage.setItem('dm_products', JSON.stringify(catalogSeed)); localStorage.setItem('dm_stores', JSON.stringify(storesSeed)); alert('Catalog ready'); return; } for(const s of storesSeed) await setDoc(doc(db,'stores',s.id), {...s, updatedAt:serverTimestamp()}, {merge:true}); const snap = await getDocs(collection(db,'products')); if(snap.empty){ for(const p of catalogSeed) await addDoc(collection(db,'products'), {...p, active:true, createdAt:serverTimestamp()}); } await setDoc(doc(db,'settings','store'), defaultSettings, {merge:true}); alert('Catalog ready'); }
async function uploadCloudinary(file, folder='devindra-mart'){ const cloud=import.meta.env.VITE_CLOUDINARY_CLOUD_NAME || 'dmwznjgvr'; const preset=import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET || 'devindra_upload'; const fd=new FormData(); fd.append('file',file); fd.append('upload_preset',preset); fd.append('folder',folder); const r=await fetch(`https://api.cloudinary.com/v1_1/${cloud}/auto/upload`,{method:'POST',body:fd}); const data=await r.json(); if(!data.secure_url) throw Error('Upload failed'); return data.secure_url; }
async function importExcel(file){ const data=await file.arrayBuffer(); const wb=XLSX.read(data); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{defval:''}); const mapped=rows.map((r,i)=>({ storeId:r.storeId||r.StoreId||MASTER, category:r.category||r.Category||'Grocery', subcategory:r.subcategory||r.Subcategory||'', product:r.product||r.Product||r.name||`Product ${i+1}`, brand:r.brand||r.Brand||'', image:r.imageUrl||r['image URL']||r.image||'/assets/products/fortune-oil.png', badge:r.badge||r['MRP badge']||'', variants:[{label:r.variant||r.Variant||r.unit||'Packet', unit:r.unit||r.Unit||'Packet', loosePrice:Number(r.loosePrice||r['loose price']||r.price||0), cartonPrice:Number(r.cartonPrice||r['carton price']||0), stock:Number(r.stock||r.Stock||0)}], scheme:r.scheme||'' })).filter(x=>x.product); if(!db){ localStorage.setItem('dm_products', JSON.stringify(mapped.map((x,i)=>({...x,id:'excel-'+i})))); alert(`Imported ${mapped.length} products`); return; } const batch=writeBatch(db); mapped.forEach(p=>batch.set(doc(collection(db,'products')), {...p, active:true, createdAt:serverTimestamp()})); await batch.commit(); alert(`Imported ${mapped.length} products`); }
function deliveryCharge(subtotal, mode='wholesale'){ if(mode==='retail') return defaultSettings.deliveryRules.retail.fixed; const r=defaultSettings.deliveryRules.wholesale.find(x=>subtotal<=x.upto); return r ? r.charge : 0; }
function pickupCode(area='WAR'){ const d=new Date(); const dt=String(d.getFullYear()).slice(2)+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'); return `${area}-${dt}-${Math.floor(1000+Math.random()*9000)}`; }
async function saveOrder(order){ if(db){ await addDoc(collection(db,'orders'), {...order, createdAt:serverTimestamp()}); } else { const old=JSON.parse(localStorage.getItem('dm_orders')||'[]'); old.unshift({...order,id:'local-'+Date.now(), createdAt:Date.now()}); localStorage.setItem('dm_orders',JSON.stringify(old)); } }
async function updateOrder(id, data){ if(!db || String(id).startsWith('local')){ const arr=JSON.parse(localStorage.getItem('dm_orders')||'[]').map(o=>o.id===id?{...o,...data}:o); localStorage.setItem('dm_orders',JSON.stringify(arr)); return; } await updateDoc(doc(db,'orders',id), {...data, updatedAt:serverTimestamp()}); }
function readLS(key, fallback){ try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback} }
function money(n){ return '₹'+Number(n||0).toLocaleString('en-IN'); }
function IconBtn({icon,label,onClick}){ return <button className="iconBtn" onClick={onClick}><span>{icon}</span><small>{label}</small></button> }
function LogoSlider(){ const logos=['/assets/logo.png','/assets/app-icon.png']; const [i,setI]=useState(0); useEffect(()=>{const t=setInterval(()=>setI(v=>(v+1)%logos.length),2200); return()=>clearInterval(t)},[]); return <div className="logoSlider"><img src={logos[i]} onError={e=>{e.currentTarget.style.display='none'}}/><b>Devindra Mart</b></div> }
function PromoSlider(){ const slides=[{type:'image',src:'/assets/banner-main.png'},{type:'video',src:'/assets/promo-video.mp4'},{type:'image',src:'/assets/cart-summary-reference.png'}]; const [i,setI]=useState(0), [mute,setMute]=useState(true); useEffect(()=>{ if(slides[i].type==='image'){ const t=setTimeout(()=>setI((i+1)%slides.length),3500); return()=>clearTimeout(t);} },[i]); return <div className="promo" id="promoSlider">{slides[i].type==='image'?<img src={slides[i].src}/>:<video src={slides[i].src} autoPlay muted={mute} playsInline onEnded={()=>setI((i+1)%slides.length)}/>} {slides[i].type==='video'&&<button className="mute" onClick={()=>setMute(!mute)}>{mute?'🔇':'🔊'}</button>} <div className="dots">{slides.map((_,idx)=><button className={idx===i?'active':''} onClick={()=>setI(idx)} key={idx}/>)}</div></div> }
function AppShell({title='Devindra Mart', subtitle='', nav=[], children, cls=''}){ return <><header className={'top '+cls}><LogoSlider/><div className="headerActions"><IconBtn icon="🎙️" label="Voice"/><IconBtn icon="🔔" label="Notify"/><IconBtn icon="🌐" label="Lang"/></div></header><main className="wrap">{subtitle&&<div className="pageTitle"><h2>{title}</h2><p>{subtitle}</p></div>}{children}</main>{nav.length>0&&<nav className="bottomNav">{nav.map(n=><span key={n}>{n}</span>)}</nav>}</> }
function LoginGate({children}){ const [profile,setProfile]=useState(()=>readLS(CUSTOMER_KEY,null)); const [addr,setAddr]=useState(()=>readLS(ADDRESS_KEY,null)); const [step,setStep]=useState(profile?'address':'login'); const [form,setForm]=useState({name:'',phone:'',state:'Bihar',district:'Samastipur',policeStation:'Warishnagar',area:'Warishnagar',shopName:'',fullAddress:'',landmark:'',pincode:''}); if(profile&&addr) return children(profile,addr); if(step==='login') return <div className="gate"><LogoSlider/><h1>Welcome</h1><p>Mobile number se login karein</p><input placeholder="Name" onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile number" inputMode="numeric" onChange={e=>setForm({...form,phone:e.target.value})}/><label className="robot"><input type="checkbox"/> I am not a robot</label><button onClick={()=>{ if(form.name&&form.phone){ localStorage.setItem(CUSTOMER_KEY,JSON.stringify({name:form.name,phone:form.phone})); setProfile({name:form.name,phone:form.phone}); setStep('address'); roleLogin('customer'); }}}>Continue</button></div>; return <div className="gate"><h2>Delivery Address</h2><div className="formGrid">{['state','district','policeStation','area','shopName','fullAddress','landmark','pincode'].map(k=><input key={k} placeholder={k.replace(/([A-Z])/g,' $1')} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button onClick={()=>navigator.geolocation?.getCurrentPosition(()=>alert('Location captured'),()=>alert('Manual address / WhatsApp location fallback'))}>Use Current Location</button><button onClick={()=>{localStorage.setItem(ADDRESS_KEY,JSON.stringify(form)); setAddr(form);}}>Save Address</button></div> }
function ProductCard({p, cart, setCart, lang}){ const [idx,setIdx]=useState(0); const v=p.variants?.[idx]||p.variants?.[0]||{}; const key=p.id+'__'+idx; const qty=cart[key]?.qty||0; const add=(q=1)=>setCart(c=>({...c,[key]:{...p, variant:v, variantIndex:idx, qty:(c[key]?.qty||0)+q}})); const minus=()=>setCart(c=>{const n={...c}; if((n[key]?.qty||0)<=1) delete n[key]; else n[key]={...n[key],qty:n[key].qty-1}; return n}); return <div className="productCard"><div className="badgeRow"><span>{p.badge}</span>{v.stock<=6&&<b>Low Stock</b>}</div><div className="productMain"><img src={p.image} onError={e=>e.currentTarget.src='/assets/logo.png'}/><div><h3>{p.product}</h3><p>{p.category} • {v.unit}</p><select value={idx} onChange={e=>setIdx(Number(e.target.value))}>{(p.variants||[]).map((x,i)=><option key={i} value={i}>{x.label} — {money(x.loosePrice)}</option>)}</select><div className="priceLine"><b>{money(v.loosePrice)} / {v.unit}</b>{v.cartonPrice? <small>{money(v.cartonPrice)} / Carton</small>:null}</div>{p.scheme&&<em>{p.scheme}</em>}</div></div><div className="bulk"><button onClick={()=>add(1)}>+1</button><button onClick={()=>add(5)}>+5</button><button onClick={()=>add(10)}>+10</button><button onClick={()=>add(1)}>Carton</button></div><div className="qtyRow">{qty?<><button onClick={minus}>−</button><strong>{qty}</strong><button onClick={()=>add(1)}>+</button></>:<button onClick={()=>add(1)}>Add</button>}</div></div> }
function CartSheet({open,setOpen,cart,setCart,store,profile,address, lang}){ const items=Object.entries(cart).map(([key,x])=>({...x,key})); const subtotal=items.reduce((s,i)=>s+i.variant.loosePrice*i.qty,0); const delivery=deliveryCharge(subtotal, store.mode); const total=subtotal+delivery; const t=T[lang]; const change=(key,d)=>setCart(c=>{const n={...c}; if(!n[key])return n; n[key]={...n[key],qty:n[key].qty+d}; if(n[key].qty<=0) delete n[key]; return n}); const place=async()=>{ if(!items.length) return; if(store.mode==='wholesale'&&subtotal<500){ alert(t.min); return; } const order={orderId:`INV-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`, customerId:localStorage.getItem('dm_uid')||'customer', customerName:profile.name, phone:profile.phone, address:address.fullAddress||address.area, landmark:address.landmark, map:'', storeId:store.id, storeName:store.name, items, subtotal, delivery, total, paymentStatus:'Submitted', paymentType:'COD', status:'Pending', pickupCode:pickupCode(address.area?.slice(0,3)?.toUpperCase()||'WAR'), createdBy:'customer'}; await saveOrder(order); localStorage.removeItem(CART_KEY); setCart({}); setOpen(false); if(store.id===MASTER){ const msg=`New Order\n\nName: ${profile.name}\nPhone: ${profile.phone}\nAddress: ${order.address}\nLandmark: ${order.landmark||''}\nMap: ${order.map||''}\n\nItems:\n${items.map(i=>`• ${i.product} (${i.variant.label}) x ${i.qty} = ₹${i.variant.loosePrice*i.qty}`).join('\n')}\n\nSubtotal: ₹${subtotal}\nDelivery: ₹${delivery}\nTotal: ₹${total}`; window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,'_blank'); } alert(t.success); }; return <>{items.length>0&&<button id="cartBar" className="cartBar" onClick={()=>setOpen(true)}><span>🛒 {items.length} Items</span><b>{t.view} • {money(total)}</b></button>}{open&&<div className="sheetOverlay"><div className="cartSheet" id="cartSheet"><div className="sheetHead"><h2>{t.cart}</h2><button onClick={()=>setOpen(false)}>×</button></div>{items.length?items.map(i=><div className="cartItem" key={i.key}><img src={i.image}/><div><b>{i.product}</b><small>{i.variant.label}</small><div><button onClick={()=>change(i.key,-1)}>−</button><span>{i.qty}</span><button onClick={()=>change(i.key,1)}>+</button></div></div><strong>{money(i.variant.loosePrice*i.qty)}</strong></div>):<p>{t.empty}</p>}<div className="totals"><p><span>{t.subtotal}</span><b>{money(subtotal)}</b></p><p><span>{t.delivery}</span><b>{money(delivery)}</b></p><p className="grand"><span>{t.total}</span><b>{money(total)}</b></p></div><button className="placeBtn" onClick={place}>{store.id===MASTER?t.whatsapp:t.order}</button></div></div>}</> }
function CustomerApp(){ const [lang,setLang]=useState(localStorage.getItem(LANG_KEY)||'hinglish'); const [store,setStore]=useState(storesSeed[0]); const products=useLiveProducts().filter(p=>p.storeId===store.id || store.id===MASTER); const [cart,setCart]=useState(()=>readLS(CART_KEY,{})); const [sheet,setSheet]=useState(false); const [view,setView]=useState('grid'); useEffect(()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart))},[cart]); useEffect(()=>{localStorage.setItem(LANG_KEY,lang)},[lang]); return <LoginGate>{(profile,address)=><AppShell nav={['🏠 Home','🏪 Shops','🛒 Cart','📒 Khata','👤 Profile']} cls="customer"><PromoSlider/><div className="noticeBar">Fresh deals today • Minimum order ₹500 • Fast delivery</div><div className="tools"><div className="search">🔍 {T[lang].search}</div><select value={lang} onChange={e=>setLang(e.target.value)}><option value="hinglish">Hinglish</option><option value="hindi">Hindi</option><option value="english">English</option></select></div><div className="chips">{['Tel/Oil','Chawal/Rice','Aata/Atta','Dal/Pulses','Masale','Namkeen','Biscuit','Cold Drink','More'].map(x=><button key={x}>{x}</button>)}</div><div className="storeBox"><b>{store.name}</b><small>{store.mode==='wholesale'?'Wholesale • Carton + Khata':'Retail • Order Now'}</small>{storesSeed.filter(s=>s.visible).length>1&&<select onChange={e=>setStore(storesSeed.find(s=>s.id===e.target.value))}><option value={MASTER}>Devindra Mart Wholesale</option>{storesSeed.filter(s=>s.visible&&s.id!==MASTER).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>}</div><div className="head"><h2>Products</h2><div><button onClick={()=>setView('grid')}>Grid</button><button className="light" onClick={()=>setView('list')}>List</button></div></div><section className={view==='grid'?'products gridProducts':'products listProducts'}>{products.map(p=><ProductCard key={p.id} p={p} cart={cart} setCart={setCart} lang={lang}/>)}</section><section className="khataBox"><h3>{T[lang].khata}</h3><p>{T[lang].due}: ₹0</p><small>{T[lang].trust}</small></section><CartSheet open={sheet} setOpen={setSheet} cart={cart} setCart={setCart} store={store} profile={profile} address={address} lang={lang}/></AppShell>}</LoginGate> }
function AdminApp(){ const [tab,setTab]=useState('dashboard'), [orders,setOrders]=useState([]), [products,setProducts]=useState([]); useEffect(()=>{roleLogin('admin'); const a=listenOrdersAll(setOrders); const b=listenProductsForAdmin(setProducts); return()=>{a();b()}},[]); const liveOrders=orders; async function upload(e){ const f=e.target.files?.[0]; if(f) await importExcel(f); } async function cloud(e){ const f=e.target.files?.[0]; if(!f)return; alert(await uploadCloudinary(f,'devindra-admin')); } return <AppShell title="Devindra Admin" subtitle="Master Control" nav={['📊 Home','📦 Products','🏪 Stores','🛵 Riders','⚙️ Settings']} cls="admin"><div className="adminTabs">{['dashboard','products','orders','settings','onboarding'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='dashboard'&&<><div className="stats"><div><b>{orders.length}</b><span>Orders</span></div><div><b>{products.length}</b><span>Products</span></div><div><b>₹0</b><span>Khata Pending</span></div><div><b>53</b><span>Low Stock</span></div></div><div className="adminGrid"><Panel title="Fast Search"><input placeholder="Rider ID, Order ID, customer, pickup code"/><button>Search</button></Panel><Panel title="Order Sound & Templates"><select><option>New order bell</option><option>Soft ping</option><option>Urgent ring</option></select><textarea placeholder="Notification template"/></Panel><Panel title="Delivery Rules"><b>Wholesale</b><p>Slab / per KM / area-wise</p><b>Retail</b><p>Fixed / per KM / hybrid</p></Panel><Panel title="Payout Rules"><p>Merchant commission, rider salary/per order/per km/bonus</p></Panel></div></>}{tab==='products'&&<div className="adminGrid"><Panel title="Excel Upload"><input type="file" accept=".xlsx,.xls,.csv" onChange={upload}/><a href="/assets/devindra-products.xlsx" download>Download sample</a></Panel><Panel title="Cloudinary Upload"><input type="file" onChange={cloud}/></Panel><Panel title="Seed Catalog"><button onClick={seedDatabase}>Seed Products</button></Panel><Panel title="Product Count"><b>{products.length}</b></Panel></div>}{tab==='orders'&&<div className="orderList">{liveOrders.map(o=><OrderAdminCard key={o.id} order={o}/>)}</div>}{tab==='settings'&&<div className="adminGrid"><Panel title="Branding"><input defaultValue="Devindra Mart"/><input defaultValue="Ab ghar tak paaye bazaar jaise rate"/></Panel><Panel title="Ads / Promo"><input type="file"/><button>ON/OFF</button></Panel><Panel title="Area / Zone"><p>Warishnagar • Khanpur • Nearby Villages</p></Panel><Panel title="Reports"><p>Sales, growth, top product, low stock, khata, profit</p></Panel></div>}{tab==='onboarding'&&<div className="adminGrid"><Panel title="Rider Requests"><p>Pending / Approved / Rejected / Suspended</p><button>Approve</button></Panel><Panel title="Merchant Requests"><p>Store mode: Wholesale / Retail / Both</p><button>Approve</button></Panel></div>}</AppShell> }
function listenProductsForAdmin(cb){ if(!db){ cb(JSON.parse(localStorage.getItem('dm_products')||'null')||catalogSeed); return ()=>{};} return onSnapshot(collection(db,'products'), s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),()=>{}); }
function listenOrdersAll(cb){ if(!db){ cb(JSON.parse(localStorage.getItem('dm_orders')||'[]')); return ()=>{};} return onSnapshot(query(collection(db,'orders'), orderBy('createdAt','desc')), s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),()=>{}); }
function Panel({title,children}){ return <div className="panel"><h3>{title}</h3>{children}</div> }
function OrderAdminCard({order}){ return <div className="orderCard"><b>{order.orderId}</b><p>{order.customerName} • {money(order.total)} • {order.status}</p><div><button onClick={()=>updateOrder(order.id,{status:'Packed'})}>Packed</button><button onClick={()=>updateOrder(order.id,{status:'Cancelled'})}>Cancel</button></div></div> }
function BillingApp(){ const [orders,setOrders]=useState([]); useEffect(()=>{roleLogin('billing'); return listenOrdersAll(setOrders)},[]); const main=orders.filter(o=>o.storeId===MASTER); return <AppShell title="Devindra Billing" subtitle="Fast billing + dispatch" nav={['📥 Orders','🖨️ Print','🛵 Riders','💰 Cash','⚙️ More']} cls="billing"><div className="stats"><div><b>{main.filter(o=>o.status==='Pending').length}</b><span>New</span></div><div><b>{main.filter(o=>o.status==='Packed').length}</b><span>Packed</span></div><div><b>{main.length}</b><span>Total</span></div></div><div className="orderList">{main.length?main.map(o=><div className="orderCard" key={o.id}><b>{o.orderId}</b><p>{o.storeName} • {money(o.total)}</p><p>Pickup code: {o.pickupCode}</p><button onClick={()=>updateOrder(o.id,{status:'Packed'})}>Ready / Print</button><button onClick={()=>window.print()}>Print Invoice</button><button>Assign Rider</button></div>):<Panel title="No Orders">Customer app se order aayega.</Panel>}</div><InvoicePreview/></AppShell> }
function InvoicePreview(){ return <div className="invoice"><h2>Devindra Mart</h2><p>“Bharose ke saath vyapar”</p><small>Founder: Aditya Jha • Contact: 7678256489 • UPI: upi@upi</small><b>INV-YYYY-000001</b></div> }
function RiderApp(){ const [orders,setOrders]=useState([]), [code,setCode]=useState(''), [den,setDen]=useState({}); useEffect(()=>{roleLogin('rider'); return listenOrdersAll(setOrders)},[]); const assigned=orders.filter(o=>['Packed','Assigned','Pending'].includes(o.status)); const unlocked=assigned.filter(o=>o.pickupCode===code); const expected=unlocked.reduce((s,o)=>s+(o.paymentType==='COD'?Number(o.total):0),0); const entered=Object.entries(den).reduce((s,[k,v])=>s+Number(k)*Number(v||0),0); return <AppShell title="Devindra Rider" subtitle="Pickup ready" nav={['🏠 Home','🔐 Unlock','💰 Cash','👤 Profile']} cls="rider"><div className="stats"><div><b>{assigned.length}</b><span>Pickup Ready</span></div><div><b>{unlocked.length}</b><span>Unlocked</span></div><div><b>{money(expected)}</b><span>COD</span></div></div><div className="pickupReady"><h2>📦 Pickup Ready</h2><p>Shop: Devindra Mart Wholesale</p><p>Orders: {assigned.length} Ready</p><small>Full details QR/code ke baad unlock honge.</small></div><div className="unlockBox"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Pickup code enter karein"/><button>Unlock</button></div>{unlocked.map(o=><div className="orderCard" key={o.id}><b>{o.orderId}</b><p>{o.customerName} • {o.address}</p><p>{money(o.total)} • {o.paymentType||'COD'}</p><ul>{o.items?.map(i=><li key={i.key}>{i.product} — {i.variant?.label} x {i.qty}</li>)}</ul><button onClick={()=>updateOrder(o.id,{status:'On The Way'})}>On The Way</button><button onClick={()=>updateOrder(o.id,{status:'Delivered'})}>Delivered</button></div>)}<div className="panel"><h3>Settlement</h3>{[500,200,100,50,20,10].map(n=><label key={n}>₹{n}<input type="number" onChange={e=>setDen({...den,[n]:e.target.value})}/></label>)}<p>Expected: {money(expected)} • Entered: {money(entered)}</p><button disabled={expected!==entered}>Submit Cash</button></div><div className="panel"><h3>Earnings</h3><p>Basic Salary ₹8000</p><p>Delivered Orders x ₹5</p><p>New Customer Bonus</p><p>Salary Date: Next month 10</p></div></AppShell> }
function AboutApp(){ return <AppShell title="About Devindra Mart" subtitle="More Information" nav={['ℹ️ About']} cls="about"><div className="panel"><h2>Devindra Mart</h2><p>Devindra Mart ek modern wholesale platform hai jo dukaano ko smart tarike se chalane me madad karta hai.</p><p><b>Founder:</b> Aditya Jha</p><p><b>Hamari soch:</b> Jahan rate bhi sahi, system bhi sahi</p></div></AppShell> }
function App(){ const path=location.pathname; if(path.startsWith('/admin')) return <AdminApp/>; if(path.startsWith('/billing')) return <BillingApp/>; if(path.startsWith('/rider')) return <RiderApp/>; if(path.startsWith('/about')) return <AboutApp/>; return <CustomerApp/> }
if('serviceWorker' in navigator) navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
createRoot(document.getElementById('root')).render(<App/>);
